name: Test react@next integration
# This workflow is triggered on pushes to the repository.
on: [push, repository_dispatch]

jobs:
  test:
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup Material-UI repository
        run: |
          git clone https://github.com/mui-org/material-ui.git
      - name: Apply Version
        run: |
          version=$(npm dist-tag ls react | grep -oP 'next: \K(.*)')
          # Laugh at me all day but bash scripts are laughable at this kind of thing
          node -p "JSON.stringify((global.package=require('./material-ui/package.json'),['react','react-dom','react-is','react-test-renderer','scheduler'].reduce((a,b)=>(a.resolutions[b]='${version}',a),global.package)),null,2)" > material-ui/package.next.json
          mv material-ui/package.next.json material-ui/package.json
          cd material-ui
          yarn
      - name: JSDOM tests
        run: |
          cd material-ui
          yarn test:unit
      - name: browser tests
        run: |
          cd material-ui
          yarn test:karma